name: Run Cypress Tests

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests and generate report
        run: |
          # Run Cypress tests and store results in a temporary directory
          mkdir -p cypress/temp_results
          npm run cy:run -- --reporter junit --reporter-options "mochaFile=cypress/temp_results/report.xml"

          # Display the test results for debugging purposes
          cat cypress/temp_results/report.xml

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-results
          path: cypress/temp_results

      - name: Run Cypress tests and save screenshots
        run: |
          # Run Cypress tests and save screenshots in the "screenshots" directory
          mkdir -p cypress/screenshots
          npm run cy:run -- --env screenshotOnRun=true

      - name: Archive Cypress screenshots
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Install mailx
        run: sudo apt-get update && sudo apt-get install -y mailutils

      - name: Send Test Report Email
        env:
          REPORT_EMAIL: ${{ secrets.TEST_REPORT_VIA_EMAIL }} # Email of the other person
          YOUR_EMAIL: d.yaroslav.grodas@gmail.com # Your email address
        run: |
          # Send the email with the test report using mailx, including the test results as attachments
          echo "Please find the test report and Cypress screenshots attached." | mailx -s "Cypress Test Report" -a cypress/temp_results/report.xml -a cypress/screenshots -r d.yaroslav.grodas@gmail.com $REPORT_EMAIL $YOUR_EMAIL
